language: cpp
compiler:
  - clang
  - gcc
cache:
  - pip: true
install:
  - mkdir temp
  - cd temp
  # install MKL
  - wget https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS-2019.PUB
  - sudo apt-key add GPG-PUB-KEY-INTEL-SW-PRODUCTS-2019.PUB
  - sudo wget https://apt.repos.intel.com/setup/intelproducts.list -O /etc/apt/sources.list.d/intelproducts.list
  - sudo apt-get update
  - sudo apt-get install intel-mkl-2018.1-038 -y
  # download eigen
  - wget http://bitbucket.org/eigen/eigen/get/3.3.4.tar.gz
  - tar -zxvf 3.3.4.tar.gz > nul
  - mv eigen-eigen-5a0156e40feb ../src/eigen-3
  - cd ..
script:
  - python3 test/test.py
