language: cpp
compiler:
  - clang
  - gcc
cache:
  - apt: true
  - directories:
    - /opt/intel/compilers_and_libraries_2018.1.163/linux/mkl
install:
  - mkdir temp -p
  - cd temp
  # install MKL
  - sudo python3 ../test/installMKL.py
  # download eigen
  - wget http://bitbucket.org/eigen/eigen/get/3.3.4.tar.gz
  - tar -zxvf 3.3.4.tar.gz > nul
  - mv eigen-eigen-5a0156e40feb ../src/eigen-3
  - cd ..
script:
  - python3 test/test.py
